version: 2
ethernets:
  interface0:
    match:
      name: en*
    addresses: [192.168.0.110/24]
    dhcp4: false
    dhcp6: false
    gateway4: 192.168.0.1
    nameservers:
      addresses: [192.168.0.1, 8.8.8.8, 8.8.4.4]
